### ISSUE TITLE
Can not open Motor in FreeCAD

### ISSUE THREAD

**Issue by timmwille** [case06/upklib_v2#8]
For some reason it is not possible to open the Model in FreeCAD 0.19, not sure where the Problem is right now but maybe it would be general good Idea to add Step files to the repo as with the stl for the printing parts is already a good solution

https://github.com/case06/upklib_v2/tree/master/electronics/motors

**Comment by case06** [comment]
For me it opens flawlessly, using FreeCAD Version 0.19 Rev. 17798 Rel. 17.08.2019

**Comment by timmwille** [comment]
works apart from some minor errors now for me as well:

![grafik](https://user-images.githubusercontent.com/8081055/146561567-8a4371f7-40aa-47ac-b630-9226933c26e1.png)


OS: Manjaro Linux (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.28263 (Git)
Build type: Release
Branch: makepkg
Hash: c6cb39697eb439caf7e5bd0208ca3082a7820547
Python version: 3.9.7
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: German/Germany (de_DE)
