### ISSUE TITLE
What FreeCAD version to use for exact replication/complication free opening of parts?

### ISSUE THREAD

**Issue by timmwille** [case06/upklib_v2#9]
Are the files consistent with the current FreeCAD Stable? at least with FreeCAD 0.19 I hade some issues and to fix some constrains/sketch references. It looks like some parts are done in older FreeCAD versions. So for each part it is best to use what FreeCAD version?

**Comment by case06** [comment]
For me it opens flawlessly, using FreeCAD Version 0.19 Rev. 17798 Rel. 17.08.2019
